# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-07 08:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karyawan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kehadiran',
            name='karyawan',
        ),
        migrations.DeleteModel(
            name='Kehadiran',
        ),
    ]
